version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

    command: >
      sh -c "[ -f manage.py ] || /py/bin/django-admin startproject app . && python manage.py runserver 0.0.0.0:8000"