name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files in the repository root
      run: ls -la

    - name: List files in the project directory
      run: ls -la ./zionstone-electro-musical # Adjust this path if needed

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or the desired version

    - name: Install dependencies
      working-directory: ./zionstone-electro-musical # Adjust this path if needed
      run: npm install

    - name: Run tests
      working-directory: ./zionstone-electro-musical # Adjust this path if needed
      run: npm test

    - name: Save test results
      run: echo "testResults=passed" >> $GITHUB_STATE

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
